// Code generated by goquery; DO NOT EDIT.

package {{.PackageName}}


func init() {
{{- range $EntityTypeName, $Callers := .Data }}
    goquery.AddToGlobalEntity[*{{$EntityTypeName}}](
        goquery.Calls{
        Where: map[goquery.Caller]goquery.QueryFunc{
        {{- range $caller, $query := $Callers}}
            goquery.Caller{File: "{{$caller.Filename}}", Line: {{$caller.Line}}}: func(helper goquery.Helper, query *bun.SelectQuery, args ...any) {
            query.Where("{{$query.Query}}",
            {{join $query.Args ", \n"}})
            },
        {{end -}}
        },
        },
    )
{{ end -}}
}
